name: CI Test

on:
  push:
    branches: [ master, stable ]
    paths-ignore:
    - '*.md'
    - '.github/**'
  pull_request:
    branches: [ master, stable ]
    paths-ignore:
    - '*.md'
    - '.github/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
            node-version: '14.18.2'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
